### ISSUE TITLE
LQX and Zen

### ISSUE THREAD

**Issue by ShalokShalom** [damentz/damentz.github.io#1]
Hi there

I see on your webpage and repo the Zen, and LXQ kernel mentioned. 
Both are created by you, and I am confused about the relationship of them. 
Do you maintain one more, do you prefer one, and does one stand on the other?
Thanks

**Comment by damentz** [comment]
Zen Kernel is a conservative enthusiast kernel to try to be overall better than stock without any major regressions.  Liquorix is highly opinionated, attempts to get better responsiveness and scheduling determinism at the cost of some features and throughput.

I co-maintain the repo for Zen Kernel, which basically is what Liquorix uses as well.  Liquorix may at times deviate but not often.

**Comment by ShalokShalom** [comment]
might be worth noting that somewhere more public
